# on:
#   schedule:
#     - cron: "0 0 * * 0" # weekly on Sunday
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    # We'll need 'contents: write' to create releases and upload assets
    permissions:
      contents: write
      packages: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      - name: Check if a new image has been pushed in the last 8 days
        run: |
          IMAGE=$(docker buildx imagetools inspect ghcr.io/codabool/fedora-bootc:latest --format "{{json .Image}}")
          CREATED=$(echo $IMAGE | jq -r .created)
          LINUX_KERNAL=$(echo $IMAGE | jq -r '.config.Labels.["ostree.linux"]')
          DISTRO_VERSION=$(echo $IMAGE | jq -r '.config.Labels.["org.opencontainers.image.version"]')

          echo "fedora-bootc image is $(( ( $(date +%s) - $(date -d "$CREATED" +%s) ) / 86400 )) days old"
          [[ $(( $(date +%s) - $(date -d "$CREATED" +%s) )) -gt $((8*86400)) ]] && exit 1

          # Convert CREATED to a simplified format (YYYY-MM-DD)
          CREATED_SIMPLE=$(echo $CREATED | cut -d'T' -f1)

          echo "creating new iso with: kernal $LINUX_KERNAL | distro $DISTRO_VERSION"

          # Set output variables for use in later steps
          echo "DISTRO_VERSION=$DISTRO_VERSION" >> $GITHUB_ENV
          echo "LINUX_KERNAL=$LINUX_KERNAL" >> $GITHUB_ENV
          echo "CREATED_SIMPLE=$CREATED_SIMPLE" >> $GITHUB_ENV
        # https://github.com/ublue-os/bootc-image-builder-action
      - uses: centos-workstation/bootc-image-builder-action@main
        with:
          # Configuration file for the image builder.
          config-file: ./bootc/config.toml
          # Image (registry with tag) used in the artifact.
          image: ghcr.io/codabool/fedora-bootc:latest
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v4
        with:
          path: ./output/bootiso/install.iso
          name: "${{ env.DISTRO_VERSION }}-${{ env.LINUX_KERNAL }}-${{ env.CREATED_SIMPLE }}"
          overwrite: true
