on:
  schedule:
    - cron: '20 0 1 * *'
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/PhrozenByte/gh-workflow-immortality
      - uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ secrets.GH_TOKEN }}
          repos: |
            CodaBool/podman
            CodaBool/r2-to-vtt
            CodaBool/caffine
            CodaBool/miniflux
